config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'boards#index'

  resources :boards
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id         :bigint           not null, primary key
#  content    :text
#  name       :string
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint
#
# Indexes
#
#  index_boards_on_user_id  (user_id)
#
class Board < ApplicationRecord
  validates :title, presence: true, length: {minimum: 3}
  validates :title, format: { with: /\A(?!\@)/ }

  validates :name, presence: true, length: {minimum: 3}

  validates :content, presence: true
  validates :content, uniqueness: true

  validate :validate_title_and_content_length

  belongs_to :user, dependent: :destroy

  def display_created_at
    I18n.l(self.created_at, format: :default)
  end

  private 
  def validate_title_and_content_length
    char_count = self.title.length + self.content.length
    if char_count < 30
      errors.add(:content, '30文字以上で！')
    end
  end


end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :boards

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show]

  def index
    @boards = Board.all
  end

  def show
  end

  def new
    @board = current_user.boards.build
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to board_path(@board), notice: '保存に成功'
    else
      flash.now[:error] = '保存に失敗'
      render :new
      # creare action中でnew.htmlを表示させている
    end
  end

  def edit
    # new actionとの違い => editはidが渡ってくる
    @board = current_user.boards.find(params[:id])
  end

  def update
    @board = current_user.boards.find(params[:id])
    if @board.update(board_params)
      redirect_to board_path(@board), notice: '更新できました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

  def destroy
    board = current_user.boards.find(params[:id])
    board.destroy!
    redirect_to root_path, notice: '削除に成功しました'
  end

  # def update
  #   @board = Board.find(params[:id])
  #   if @board.update(board_params)
  #     redirect_to board_path, notice: '変更に成功'
  #   else
  #     flash.now[:error] = '保存に失敗しました'
  #     render :edit
  #   end
  # end

  private
    def board_params
      params.require(:board).permit(:title, :name, :content)
    end

    def set_board
      @board = Board.find(params[:id])
    end

end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/boards/edit.html.haml
.container
  %ul
    - @board.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @board, url: board_path(@board), method: 'put', local: true) do |f|
    %div
      = f.label :title, 'タイトル'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :name, '名前'
    %div
      = f.text_field :name, class: 'name'
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content
    = f.submit '変更確定', class: 'btn-primary'

app/views/boards/index.html.haml
.container
  .tab.pb-3
    .text-center{:class => "tab-item,"}
      %p.display-2 Board
  - @boards.each do |board|
    = link_to board_path(id: board.id) do
      .card
        .card-title.text-success
          %p.display-5
            タイトル: #{board.title}
        .card-name.text-primary
          %p.display-5
            名前: #{board.name}
        .card-content.text-danger
          %p.display-5
            内容: #{board.content}
        %div
          %p taishi0616
          %p= board.display_created_at
  = link_to new_board_path do
    .float_btn
      %i.fa.fa-plus

app/views/boards/new.html.haml
.container
  %ul
    - @board.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @board, url: boards_path, method: 'post', local: true) do |f|
    %div
      = f.label :title, 'タイトル'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :name, '名前'
    %div
      = f.text_field :name, class: 'name'
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content
    = f.submit '保存', class: 'btn-primary'

app/views/boards/show.html.haml
.board
  %h1.board_title
    ＜#{@board.title}＞
  .board_name
    %p
      名前： #{@board.name}
  .board_content
    %p
      内容： #{@board.content}
  %div
    %p [taishi0616]
    %p
      [#{@board.display_created_at}]
  .board_detail_actions
    .dropdown
      .dropdown-content
        = link_to  edit_board_path(@board), class: 'btn btn-success' do
          %i.fa.fa-edit
          %span 編集
        = link_to  root_path(@board), method: :delete, data: {confirm: '本当に削除しますか？'}, class: 'btn btn-success' do
          %i.fa.fa-remove
          %span 削除
  = link_to root_path do
    .float_btn
      %i.fa.fa-arrow-left

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Todo
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/
  %body
    = yield
    - if flash.present?
      .flash
        - flash.each do |key, value|
          %div
            = key
            = value